name: Music Auto Downloader

on:
  workflow_dispatch:

jobs:
  music:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

      - uses: actions/checkout@v4

      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip lftp curl
          pip3 install -U yt-dlp


      - name: Download via Invidious
        run: |

          mkdir -p upload

          yt-dlp \
            "https://youtu.be/E3QiD99jPAg" \
            --extractor-args "youtube:player_skip=webpage,configs" \
            --force-ipv4 \
            --extract-audio \
            --audio-format mp3 \
            --audio-quality 0 \
            --add-metadata \
            --embed-thumbnail \
            -o "upload/%(title).100s.%(ext)s"

          echo "FILES:"
          find upload || true


      - name: Upload FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          FTP_DIR: ${{ secrets.FTP_DIR }}
        run: |

          lftp -d -e "
          set ssl:verify-certificate no;
          set ftp:passive-mode on;
          open ftp://$FTP_USER:$FTP_PASS@$FTP_HOST;
          mkdir -p $FTP_DIR;
          mirror -R upload $FTP_DIR;
          bye;
          "
