name: test music

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install
      run: |
        sudo apt update
        sudo apt install -y ffmpeg
        pip install yt-dlp

    - name: run script
      run: python script.py
